apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-service
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: "10.100.166.227"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-space
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==